defaults:
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

run_mode: 'train'

custom:
  parametrized: true
  turbulent: true 

network_dir: "./"
initialization_network_dir: ""

sheduler:
  decay_rate: 0.95
  decay_steps: 10000

training:
  rec_validation_freq: 10000
  rec_inference_freq: 10000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 10000 #1500000 # one mill

batch_size:
  Inlet: 100 #500
  Outlet: 100 #500
  NoSlip: 1000 #10000
  InteriorLR: 200 #2000
  InteriorHR: 200 #2000
  IntegralContinuity: 1000 # 10000