defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
  
jit: false
run_mode: "train"

custom:
  parameteized: true
  turbulent: true

network_dir : "./"
initialization_network_dir : "../three_fin_flow"

scheduler:
  decay_rate: 0.95
  decay_steps: 10000
  
training:
  rec_validation_freq: 1000
  rec_inference_freq: 10000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 1500000
  
batch_size:
  Inlet: 100 #500
  Outlet: 100 #500
  ChannelWalls: 100 #500
  SolidInterface: 100 #500
  HeatSource: 500 # 5000
  InteriorLR: 1000 # 2000
  InteriorHR: 1000 # 2000
  SolidInterior: 1000 #1000